name: Rain SMS Alert

on:
  schedule:
    - cron: '0 */3 * * *'

  workflow_dispatch:

jobs:
  weather-alert:
    runs-on: ubuntu-latest

    env:
      OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
      TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
      TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
      FROM_NUMBER: ${{ secrets.FROM_NUMBER }}
      TO_NUMBER: ${{ secrets.TO_NUMBER }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install requests twilio

      - name: Run Weather Alert Script
        run: python main.py
